"""add trace_id to jobs for indexing event traces

Revision ID: 4981c871f1ad
Revises: 581613194df6
Create Date: 2026-09-04 02:02:10.668019
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4981c871f1ad'
down_revision: str | None = '581613194df6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('trace_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_jobs_trace_id'), 'jobs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_trace_id'), table_name='jobs')
    op.drop_column('jobs', 'trace_id')
    # ### end Alembic commands ###
